# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='Post',
        ),
    ]
