# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170611_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='article',
            new_name='post',
        ),
    ]
